runtime: python39
handlers:
- url: /(.*\.css)
  static_files: style.css
  upload: style.css
- url: /order.html
  static_files: order.html
  upload: order.html
- url: /menu.html
  static_files: menu.html
  upload: menu.html
- url: /contact.html
  static_files: contact.html
  upload: contact.html
- url: /account.html
  static_files: account.html
  upload: account.html  
- url: /.*
  static_files: index.html
  upload: index.html
